#!/bin/sh

NAME=$1
HOST=$2

deploy() {

SRC=$1
DST=/var/www/netboot/$(basename $SRC)
echo "$SRC -> $DST"

ARGS=$(jq -c . <<EOF
{
    "src": "$SRC",
    "dest": "$DST",
    "owner": "_nbd",
    "group": "www",
    "mode": "0640",
    "force": "true"
}
EOF
)

ansible \
    -i $HOST,\
    -e "@$HOME/.secrets/ansible_vault.yml" \
    --become-method=doas \
    --become \
    -a "$ARGS" \
    -m copy \
    $HOST
}

cp bin/${NAME}.iso /mnt/beaker/h/vmware/iso
deploy bin/${NAME}.iso
deploy bin/${NAME}.img
for MENU in menus/${NAME}.ipxe; do
    deploy $MENU
done

