#!/bin/sh

NAME=$1
HOST=$2

deploy() {

SRC=$1
DST=$2

DST=/var/www/netboot/$DST
echo "$SRC -> $DST"

ARGS=$(jq -c . <<EOF
{
    "src": "$SRC",
    "dest": "$DST",
    "owner": "_nbd",
    "group": "www",
    "mode": "0640",
    "force": "true"
}
EOF
)

ansible \
    -i $HOST,\
    -e "@$HOME/.secrets/ansible_vault.yml" \
    --become-method=doas \
    --become \
    -a "$ARGS" \
    -m copy \
    $HOST
}

cp bin/${NAME}.iso /mnt/beaker/h/vmware/iso
deploy bin/${NAME}.iso ${NAME}.iso
deploy bin/${NAME}.img ${NAME}.img
deploy menus/netboot.png netboot.png
deploy menus/${NAME}.ipxe ${NAME}.ipxe
deploy menus/${NAME}-openbsd.ipxe ${NAME}-openbsd.ipxe
deploy menus/${NAME}-debian.ipxe ${NAME}-debian.ipxe
